version: 0.2
phases:
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - php bin/phpunit
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes